# conda-env.yml
# Configuration file for creating a Conda Environment with dependencies needed for
# spt_ecmwf_autorapid_process.
# Create the environment by running the following command (after installing Miniconda):
# os: linux
#   $ conda env create -f conda_env.yml

name: spt
channels:
- conda-forge
- defaults
dependencies:
- python=2
- libffi
- openssl
- pycrypto
- rapidpy
- pip:
    - requests_toolbelt
    - tethys_dataset_services
    - condorpy
